/**
 * Códigos de erro estáveis do Atlas.
 *
 * O front-end deve reagir ao CÓDIGO, nunca à mensagem — mensagens
 * mudam com tradução e revisão de texto; códigos são contrato.
 */

export const ERROR_CODES = {
  // Genéricos
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  // Autenticação / autorização
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  OAUTH_FAILED: 'OAUTH_FAILED',

  // Cadastro e senha — códigos separados para o front destacar o campo
  // exato do formulário em vez de um erro genérico.
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  CPF_ALREADY_REGISTERED: 'CPF_ALREADY_REGISTERED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  /** A conta existe, mas entrou por Google e ainda não definiu senha. */
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',
  /** A conta nunca foi ativada: precisa passar pelo primeiro acesso. */
  FIRST_ACCESS_REQUIRED: 'FIRST_ACCESS_REQUIRED',
  /** Código de ativação errado, expirado ou já usado. */
  ACTIVATION_CODE_INVALID: 'ACTIVATION_CODE_INVALID',

  // Domínio
  USER_INACTIVE: 'USER_INACTIVE',
  GYM_BLOCKED: 'GYM_BLOCKED',
  WORKOUT_SESSION_ALREADY_OPEN: 'WORKOUT_SESSION_ALREADY_OPEN',
  WORKOUT_SESSION_NOT_OPEN: 'WORKOUT_SESSION_NOT_OPEN',

  // Infra / sincronização
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  ALL_DATABASES_UNAVAILABLE: 'ALL_DATABASES_UNAVAILABLE',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  SYNC_IN_PROGRESS: 'SYNC_IN_PROGRESS',
  STALE_VERSION: 'STALE_VERSION',

  // Integrações
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_DISABLED: 'AI_DISABLED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
